### ISSUE TITLE
:bug: [想定外の動作] Python-6の動作について

### ISSUE THREAD

**Issue by s1204IT** [HidemaruOwO/Awesome-HelloWorld#45]
### 言語及び作品番号

python-6

### 詳細な情報

セルフホスティングするまではいいのだが、それをコマンドラインに出力できていない。

### 想定動作
個人的なものだが、
ホスティング -> Getリクエスト(127.0.0.1:8000) -> ホスト終了 -> スクリプト終了
この様な形が好ましいと思う。

**Comment by HoneyHoney-Bee** [comment]
- **「詳細な情報」に関して**
「それをコマンドラインに出力できていない。」とありますが，"それ"とは何を指しているのでしょうか。
 - **「想定動作」に関して**
Pythonでスクリプトの動作を停止するには，`sys.exit()`を使用すればよいのですが，挿入できる場所がありません。（`return`後に入れても実行されません。）
別スレッドで停止処理を呼び出すしかないと思います。

**Comment by HidemaruOwO** [comment]
おそらく''それ''はlocalhost:8000のレスポンスかと。

**Comment by HoneyHoney-Bee** [comment]
`localhost:8000`のレスポンスというと`Hello World!!`のこと？
これをコンソールに出力すればいい、ということであれば書き直します。

**Comment by s1204IT** [comment]
> `localhost:8000`のレスポンスというと`Hello Word!!`のこと？ これをコンソールに出力すればいい、ということであれば書き直します。

そういうことです。

```
timeout-minutes: 1
continue-on-error: true
```

今の状態だと、制限時間に達するまでインスタンスがずっと回り続けてる状態なので、無理やり終了させています。
Pythonに全然詳しくないので是非ともよろしくお願いします。

**Comment by HoneyHoney-Bee** [comment]
なるほど。ちょっとコードがややこしくなりそうですが，終了させるように変更してみます。

**Comment by s1204IT** [comment]
よろしくお願いします。

**Comment by HoneyHoney-Bee** [comment]
#47 及び #48 にて対応しましたので，ご確認ください。

**Comment by s1204IT** [comment]
ありがとうございます！！

**Comment by s1204IT** [comment]
![Screenshot_20230302_004539_Chrome](https://user-images.githubusercontent.com/52069677/222190008-e2aa7f12-d951-4f3d-af22-9cee5aa8ea52.png)
マージしましたけど、直ってなかったですね...
~~確認しなかった僕が悪いのですが~~

**Comment by s1204IT** [comment]
> `localhost:8000`のレスポンスというと`Hello World!!`のこと？ これをコンソールに出力すればいい、ということであれば書き直します。

要は、このレスポンスを同じスクリプト内で取得し出力し、
出力したらホストを終了する みたいな形にして欲しいです。(自分でやれ定期)

**Comment by HoneyHoney-Bee** [comment]
![090809D3-7D44-4741-B4A3-9BF76F691657](https://user-images.githubusercontent.com/80945906/222191355-d7043ed3-abab-4a1b-80a5-7469cb0c45c8.jpeg)

 Ubuntu Server 22.04，Python 3.11の環境で動作確認しましたが，想定通りの動作でした。
＊サーバーの都合で、ホストとポートは変えてあります。

**Comment by s1204IT** [comment]
本当ですね。
ワークフローの構成も同じなのですけどね...

**Comment by HoneyHoney-Bee** [comment]
あ，今気づきました。`GitHub Actions`のことなんですね。
`http://127.0.0.1:8000`にアクセスしないとプロセスキルに発火しないので，タイムアウトになっていると思われます。

**Comment by s1204IT** [comment]
そもそもが言葉足らずで申し訳無いです...

**Comment by HoneyHoney-Bee** [comment]
GitHub Actionsのエラー回避のために10秒程度で強制終了するように書き換えます。

**Comment by s1204IT** [comment]
強制終了自体はそのまま(一度アクセスしたら発火)で大丈夫なのですが、
ホストを建ててから同じPythonスクリプト内で http://127.0.0.1:8000 にGetリクエストをして､ そのレスポンス出力する事は可能でしょうか？

**Comment by HoneyHoney-Bee** [comment]
> 強制終了自体はそのまま(一度アクセスしたら発火)で大丈夫なのですが、
> ホストを建ててから同じPythonスクリプト内で http://127.0.0.1:8000 にGetリクエストをして､ そのレスポンス出力する事は可能でしょうか？

可能です。そちらのほうがよろしければ，再度書き換えますがどうしましょうか。

**Comment by s1204IT** [comment]
そちらでよろしくお願いします。
情弱の相手をして頂きありがとうございます。

**Comment by HoneyHoney-Bee** [comment]
以上を踏まえて #50 及び #51 にて対応しました。

**Comment by s1204IT** [comment]
ありがとうございました。
終了ステータスについては目を瞑ります

**Comment by HoneyHoney-Bee** [comment]
こちらこそありがとうございました。
強制終了ということになるので，終了コードが137になるのはどうしようもありません…
