### ISSUE TITLE
✨   WorkflowでPythonを実行する時Shebangを使うのをやめることの提案

### ISSUE THREAD

**Issue by shiumano** [HidemaruOwO/Awesome-HelloWorld#65]
### 言語及び作品番号

python-4

### 詳細な情報

標準設定のNanoで開いた場合、赤色の文字があります
![Screenshot_20230302-233550](https://user-images.githubusercontent.com/75152752/222459104-291018a1-9ca7-443b-b1bd-ef5709916104.png)

**Comment by HidemaruOwO** [comment]
Pythonのshebangがダメということでしょうか？

**Comment by shiumano** [comment]
というより、コメントですね

**Comment by shiumano** [comment]
なぜシバンが必要なんですか？

**Comment by HidemaruOwO** [comment]
確かにそうですね。
ではshebangを消してpython3 file/path.pyで実行するようにします。

**Comment by shiumano** [comment]
シューゴさんにメンションしてもいいかな…?

**Comment by HidemaruOwO** [comment]
@s1204IT 私はこのことに賛成ですが、シューゴさんはどう思われますか？

**Comment by s1204IT** [comment]
ファイル単体で実行できるようにする為です。
僕が所有しているリポでは無いので、どちらでも良いです。

**Comment by s1204IT** [comment]
![image](https://user-images.githubusercontent.com/52069677/222465448-763690b0-f3b8-4d73-ab6b-7b0805428b60.png)
毎回実行権限を渡していますが、Windowsの方も多いようなので...

**Comment by shiumano** [comment]
> ![image](https://user-images.githubusercontent.com/52069677/222465448-763690b0-f3b8-4d73-ab6b-7b0805428b60.png) 毎回実行権限を渡していますが、Windowsの方も多いようなので...

…ん?(理解できていない)

**Comment by HidemaruOwO** [comment]
@s1204IT 私は、言語に対するGitHub Actionsの利用目的は、「ソースコードが正常に動作するかどうかを確認すること」だと解釈していますので、Windowsについて心配する必要はないと思います。

> ファイル単体で実行できるようにする為です。
> 僕が所有しているリポでは無いので、どちらでも良いです。

したがって、上記のご返信を了承の意味として理解したため、明日Pythonファイルの全てからシバンを削除し、ワークフローの`run:`を`./path/to/file.py`から`python3 ./path/to/file.py`に変更する予定です。
