### ISSUE TITLE
:1st_place_medal: Pythonからシバンを削除し、Workflowの実行部分をファイル実行からPython3呼び出しに変更する

### ISSUE THREAD

**Issue by HidemaruOwO** [HidemaruOwO/Awesome-HelloWorld#66]
### Pull request / Issue 割振番号

#65 

### 詳細

シバンは良くないという指摘を受けたので、変更します。

**Comment by s1204IT** [comment]
在った方が良いのは確実ですけどね。
少なくとも「コメント」では無いです。
エディタが「 **#** 」以降の文字列をコメントと認識しているだけです。
